/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/Autocomplete.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TextField: typeof import('./src/components/TextField.vue')['default']
  }
}
