/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/lib/Autocomplete.vue')['default']
    AutoCompleteItem: typeof import('./src/lib/Filter/Legacy/components/AutoCompleteItem.vue')['default']
    CallbackActionButton: typeof import('./src/lib/TiptapEditor/Extensions/CallbackActionButton.vue')['default']
    DateItem: typeof import('./src/lib/Filter/Legacy/components/DateItem.vue')['default']
    Datepicker: typeof import('./src/lib/Datepicker.vue')['default']
    DatePicker: typeof import('./src/lib/Form/VXDatePicker/DatePicker.vue')['default']
    DatePickerBase: typeof import('./src/lib/Form/VXDatePicker/DatePickerBase.vue')['default']
    DateRangeItem: typeof import('./src/lib/Filter/Legacy/components/DateRangeItem.vue')['default']
    Datetimepicker: typeof import('./src/lib/Datetimepicker.vue')['default']
    DatetimeRangeItem: typeof import('./src/lib/Filter/Legacy/components/DatetimeRangeItem.vue')['default']
    Filter: typeof import('./src/lib/Filter/index.vue')['default']
    FilterButton: typeof import('./src/lib/Filter/Legacy/components/FilterButton.vue')['default']
    FilterButtonBody: typeof import('./src/lib/Filter/Legacy/components/FilterButtonBody.vue')['default']
    ImageGlue: typeof import('./src/lib/TiptapEditor/Extensions/ImageGlue.vue')['default']
    ItemFilter: typeof import('./src/lib/Filter/Legacy/components/ItemFilter.vue')['default']
    Legacy: typeof import('./src/lib/Filter/Legacy/index.vue')['default']
    LinkageSelect: typeof import('./src/lib/LinkageSelect.vue')['default']
    LinkageSelectItem: typeof import('./src/lib/Filter/Legacy/components/LinkageSelectItem.vue')['default']
    LinkageSelectItemRemote: typeof import('./src/lib/Filter/Legacy/components/LinkageSelectItemRemote.vue')['default']
    LinkageSelectRemote: typeof import('./src/lib/LinkageSelectRemote/index.vue')['default']
    LinkSelectAutoComplete: typeof import('./src/lib/LinkageSelectRemote/components/LinkSelectAutoComplete.vue')['default']
    MessageListener: typeof import('./src/lib/MessageListener.vue')['default']
    MultipleSelectItem: typeof import('./src/lib/Filter/Legacy/components/MultipleSelectItem.vue')['default']
    NumberItem: typeof import('./src/lib/Filter/Legacy/components/NumberItem.vue')['default']
    Overlay: typeof import('./src/lib/Overlay.vue')['default']
    RangePicker: typeof import('./src/lib/Form/VXDatePicker/RangePicker.vue')['default']
    RestoreScrollListener: typeof import('./src/lib/RestoreScrollListener.vue')['default']
    ScrollIframe: typeof import('./src/lib/ScrollIframe.vue')['default']
    SelectItem: typeof import('./src/lib/Filter/Legacy/components/SelectItem.vue')['default']
    SelectMany: typeof import('./src/lib/SelectMany.vue')['default']
    SendVariables: typeof import('./src/lib/SendVariables.vue')['default']
    StringItem: typeof import('./src/lib/Filter/Legacy/components/StringItem.vue')['default']
    TextDatepicker: typeof import('./src/lib/TextDatepicker.vue')['default']
    TimeSelect: typeof import('./src/lib/Form/VXDatePicker/TimeSelect.vue')['default']
    TiptapEditor: typeof import('./src/lib/TiptapEditor/TiptapEditor.vue')['default']
    VXAvatar: typeof import('./src/lib/VXAvatar.vue')['default']
    VXCheckbox: typeof import('./src/lib/Form/VXCheckbox.vue')['default']
    VXDialog: typeof import('./src/lib/Common/VXDialog.vue')['default']
    VXField: typeof import('./src/lib/Form/VXField.vue')['default']
    VXLabel: typeof import('./src/lib/Common/VXLabel.vue')['default']
    VXSelect: typeof import('./src/lib/Form/VXSelect.vue')['default']
    VXToolBar: typeof import('./src/lib/Common/VXToolBar.vue')['default']
  }
}
